First build (Views, colors, shadow, without correct constraints)
Ytsyy/iosSchool_HH pull request #13
Opened 2023-11-27 01:41 UTC by Ytsyy

2023-11-28 15:20 UTC, vaganova-ann requested changes
1) А проект собирается? у меня ругается на файл ApiClient
2) Почему кнопки такие высокие? в фигме высота 40
3) Давай один из констрейнтов по оси У будет низкоприоритетный, а другой с неравенством, но не так, что они оба разом и низкоприоритетные, и с неравенством

2023-11-28 15:20 UTC, vaganova-ann commented on iosSchool_HH/Modules/Registration/RegistrationView.swift
> +
функции разделяет одна пустая строка

2023-11-28 15:20 UTC, vaganova-ann commented on iosSchool_HH/Modules/Registration/RegistrationView.swift
> +    func registrationTextFieldSettings(textField: UITextField){
добавь пробел между ) {

2023-11-28 15:20 UTC, vaganova-ann commented on iosSchool_HH/Modules/Registration/RegistrationView.swift
> +        button.titleLabel?.textColor = UIColor(.white)
попробуй функцию setTitleColor и убери здесь пустую строчку

2023-11-28 15:20 UTC, vaganova-ann commented on iosSchool_HH/Modules/Registration/RegistrationView.swift
> +    func registratinViewShadowSettings<T: UIView>(_ view: T) {
очень хорошо

2023-11-28 15:20 UTC, vaganova-ann commented on iosSchool_HH/Modules/Registration/RegistrationView.swift
> +extension UITextField{
давай вынесем в отдельный файл, который назовем UITextField+LeftPadding

2023-11-29 07:27 UTC, Ytsyy commented on iosSchool_HH/Modules/Registration/RegistrationView.swift
> +        button.titleLabel?.textColor = UIColor(.white)
Меня смутила гора свойств подряд и я решил для удобочитаемости разделить блоки пустыми строками - настройки текста, настройки кнопки, настройки теней (которые в итоге решил вообще выделить в отдельную функцию)

2023-11-29 07:34 UTC, Ytsyy commented on iosSchool_HH/Modules/Registration/RegistrationView.swift
> +extension UITextField{
пачиму.....
А если серьезно обязательно ли такие небольшие дополнения класса выносить ? (Или это сделано с расчетом на то что в будущем нам понадобится  это расширение вновь)

2023-11-29 14:33 UTC, vaganova-ann approved these changes

2023-11-30 08:43 UTC, merged