Twelfth-homework Done
Ytsyy/iosSchool_HH pull request #18
Opened 2023-12-07 12:35 UTC by Ytsyy

2023-12-09 14:34 UTC, vaganova-ann requested changes

2023-12-09 14:34 UTC, vaganova-ann commented on iosSchool_HH/Assembly.swift
> +    lazy var imageService: ImageServicesImp = ImageServicesImp(apiClient: apiClient)
все было правильно
lazy var imageService: ImageService = ImageServiceImp(apiClient: apiClient)

2023-12-09 14:34 UTC, vaganova-ann commented on iosSchool_HH/Modules/Character/CharacterViewController.swift
> +    private let imageService: ImageServicesImp
и здесь тоже  везде используем тип ImageService

2023-12-09 14:34 UTC, vaganova-ann commented on iosSchool_HH/Services/ImageService.swift
> +    private var imageCache = NSCache<NSString, UIImage>()
чем тебя не устроил словарь ?
 private var imageDict: [String: UIImage] = [:]

2023-12-09 14:34 UTC, vaganova-ann commented on iosSchool_HH/Services/ImageService.swift
> +        downloadImage(url: url) { [weak self] image in
а где у нас здесь загрузка изображения в отдельном потоке?

2023-12-09 14:34 UTC, vaganova-ann commented on iosSchool_HH/Services/ImageService.swift
> +                self?.clearCacheIfNeeded()
получается, что скачали изображение и тут же его удалили. лучше наоборот, сначала чистить сохраненные

2023-12-09 14:34 UTC, vaganova-ann commented on iosSchool_HH/Services/ImageService.swift
> +            if let image = image {
думаю с гардом будет чище

2023-12-09 14:34 UTC, vaganova-ann commented on iosSchool_HH/Services/ImageService.swift
> +    private func downloadImage(url: String, completion: @escaping (UIImage?) -> Void) {
эта функция и функция ниже не нужны, все можно довольно компактно вместить в getImage

2023-12-11 07:01 UTC, Ytsyy commented on iosSchool_HH/Services/ImageService.swift
> +    private func downloadImage(url: String, completion: @escaping (UIImage?) -> Void) {
Просто решил разделить функционал - получается что у нас ода функция и решает нужно ли качать или брать из словаря картинку, и управляет размером словаря, и реализует асинхронную закачку изображения если нужно
Понятно что все это нужно чтобы выполнить одну функцию - получить картинку, однако разве мы не должны разделять 1 функция = 1 задача ?

2023-12-11 14:28 UTC, vaganova-ann commented on iosSchool_HH/Services/ImageService.swift
> +                    DispatchQueue.main.async {
completion здесь и ниже не обязательно исполнять в главном потоке, это уже будет отвественность тех, кто вызывает сервис

2023-12-11 14:28 UTC, vaganova-ann commented on iosSchool_HH/Services/ImageService.swift
> +                    if self?.imageDict.count ?? 0 >= 50 {
можно удаление вообще вынести из DispatchQueue.global().async

2023-12-11 14:28 UTC, vaganova-ann commented on iosSchool_HH/Services/ImageService.swift
> +    private func downloadImage(url: String, completion: @escaping (UIImage?) -> Void) {
1 функция = 1 задача это хороший подход, но не обязательный

2023-12-18 14:08 UTC, vaganova-ann approved these changes

2023-12-20 08:13 UTC, merged