Eleventh homework
Ytsyy/iosSchool_HH pull request #24
Opened 2023-12-24 17:20 UTC by Ytsyy

2023-12-28 08:38 UTC, vaganova-ann requested changes
1) экран авторизации на дизайне темнее, чем сейчас
2) вью под лейблами на экране авторизации должна быть более заметная
3) на ксибе authViewImp красная ошибка верстки
4) в LocationCell проверить, чтобы не было констрейнтов в стеквью кроме констрейнтов размера для стрелочки

2023-12-28 08:38 UTC, vaganova-ann commented on iosSchool_HH/AppCoordinator.swift
> +        let navVC2 = assembly.rootNavigationController()
для второго экрана на таббаре не нужно создавать NavigationController, userProfileVC просто кладется в таббар в 57 строчке

2023-12-28 08:38 UTC, vaganova-ann commented on iosSchool_HH/Modules/Location/LocationView.swift
> +        tableView.contentInset = UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 0)
нужно вернуть

2023-12-28 08:38 UTC, vaganova-ann commented on iosSchool_HH/Modules/Location/Subviews/LocationCell.swift
> +    @IBOutlet private weak var chevron: UIImageView!
можно не добавлять сюда chevron и bottomLine, они все равно не используются в этом файле

2023-12-28 08:38 UTC, vaganova-ann commented on iosSchool_HH/Modules/Registration/RegistrationView.swift
> +            )
скобочка уехала

2023-12-28 08:38 UTC, vaganova-ann commented on iosSchool_HH/Modules/Registration/RegistrationViewController.swift
> +            DispatchQueue.main.async {
здесь мы не переходим в другой поток, можно DispatchQueue.main.async не вызывать

2023-12-28 08:38 UTC, vaganova-ann commented on iosSchool_HH/Modules/Registration/RegistrationViewController.swift
> +            self.onRegistrationSuccess?()
кложуру надо выполнить последнюю

2023-12-28 08:38 UTC, vaganova-ann commented on iosSchool_HH/Modules/Auth/AuthView.swift
> +    func implementBasicViewShadowSettings<T: UIView>(_ view: T) {
у тебя там были Base классы для текствью, почему бы все настройки из этой функции не перенести туда?

2023-12-28 09:00 UTC, Ytsyy commented on iosSchool_HH/Modules/Auth/AuthView.swift
> +    func implementBasicViewShadowSettings<T: UIView>(_ view: T) {
Подумал чтобы логичнее было оставить всю реализацию теней в каждом вью (потому что тени отличаются ), а реализацию UI текст филдов вынести отдельно, но действительно лучше будет тени убрать туда,

2023-12-28 09:05 UTC, Ytsyy commented on iosSchool_HH/Modules/Registration/RegistrationViewController.swift
> +            DispatchQueue.main.async {
Просто была ошибка с многопоточностью и я все UI элементы убирал в главный поток чтобы наверняка не словить ошибку еще раз

2023-12-28 09:13 UTC, Ytsyy commented on iosSchool_HH/Modules/Location/LocationView.swift
> +        tableView.contentInset = UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 0)
Не до конца понял в чем смысл этих 4 поинтов сверху (учитывая что это всего 10% от размера ячейки и почти незаметно) поэтому решил убрать

2023-12-29 08:15 UTC, vaganova-ann requested changes
1) в authViewImp лучше задать высоту для вью с лейблами, чем лейблу внутри
2) зачем в authViewImp высота для стеквью? их высота расчитается  автоматически по контенту внутри

2023-12-29 08:15 UTC, vaganova-ann commented on iosSchool_HH/AppCoordinator.swift
> +        let navVC2 = assembly.rootNavigationController()
вообще убираем переменную navVC2, потом делаем
tabVC.setViewControllers([navVC1, userProfileVC], animated: false)

2023-12-29 08:15 UTC, vaganova-ann commented on iosSchool_HH/Modules/Auth/AuthView.swift
>          loginTextField.setLeftPaddingInTextfield(padding: 16)
кстати текстфилды у нас не белые в дизайне

2024-01-07 11:22 UTC, merged