First homework done
Ytsyy/iosSchool_HH pull request #4
Opened 2023-10-28 09:11 UTC by Ytsyy

2023-10-28 10:14 UTC, vaganova-ann requested changes
1) Названия файлов пишем с большой буквы и camelCase
2) заголовок файла можно не удалять

2023-10-28 10:14 UTC, vaganova-ann commented on iosSchool_HH/first-homework.swift
> +    enum Gender: String, CaseIterable {
1) Перенеси енамы в начало класса Character, до объявления свойств
2) Внимательно прочитай условие задания для enum Gender и enum Status,  обрати внимания на строковые значения для вариантов перечисления

2023-10-28 10:14 UTC, vaganova-ann commented on iosSchool_HH/first-homework.swift
> +    init(id: Int,
Открывающая и закрывающая скобки должны быть на отдельный строчках:
init(
id: Int,
name: String,
species: String
итд
) {

2023-10-28 10:14 UTC, vaganova-ann commented on iosSchool_HH/first-homework.swift
> +class CharacterGenerator: Character {
Почему CharacterGenerator наследник Character?

2023-10-28 10:14 UTC, vaganova-ann commented on iosSchool_HH/first-homework.swift
> +        let randomGender = Gender.allCases.randomElement() ?? .unknown
можно не заводить переменные, которые используются один раз в своей области видимости

2023-10-28 10:14 UTC, vaganova-ann commented on iosSchool_HH/first-homework.swift
> +            status: randomStatus)
закрывающую скобку переставь на отдельную строку

2023-10-29 07:31 UTC, Ytsyy commented on iosSchool_HH/first-homework.swift
> +    struct Info {
Обязательно ли всегда структуры объявлять свойствами ?

2023-10-29 07:33 UTC, Ytsyy commented on iosSchool_HH/first-homework.swift
> +class CharacterGenerator: Character {
Хотел получить доступ к свойствам класса и подумал что логично будет показать связь классов, понял что можно реализовать все и без этого

2023-10-29 08:21 UTC, vaganova-ann commented on iosSchool_HH/first-homework.swift
> +    struct Info {
Будем считать, что на нашем учебном проекте да) на рабочих проектах зависит от вкуса техлида

2023-10-29 08:25 UTC, vaganova-ann requested changes

2023-10-29 08:25 UTC, vaganova-ann commented on iosSchool_HH/FirstHomework.swift
> +        case unknown = "Unkwown"
"Внутри класса определите два enum: Gender cо строковыми значениями Female, Male, Genderless и unknown, и Status со строковыми значениями Alive, Dead, unknown." - регистр в дальнейшем повлияет на получение данных с сервера, строковые значения в обоих случаях должны соответствовать условию

2023-10-30 04:16 UTC, Ytsyy commented on iosSchool_HH/FirstHomework.swift
> +        case unknown = "Unkwown"
Дело было в одной букве, понял принял

2023-10-30 04:27 UTC, vaganova-ann approved these changes

2023-10-30 05:12 UTC, merged