Third homework done
Ytsyy/iosSchool_HH pull request #8
Opened 2023-11-05 13:20 UTC by Ytsyy

2023-11-06 06:50 UTC, vaganova-ann requested changes

2023-11-06 06:50 UTC, vaganova-ann commented on iosSchool_HH/FirstHomework.swift
> +        let randomID = Int.random(in: 0...1000)
Давай не будем заводить переменные, которые используются один раз, в этом случае все можно вызвать в completion. Поправь во всех четырех функциях

2023-11-06 06:50 UTC, vaganova-ann commented on iosSchool_HH/FirstHomework.swift
> +    let generateNameTwoClosure: () -> String = {
1) переменные пишем вначале класса
2) эта кложура где-то используется?

2023-11-06 06:50 UTC, vaganova-ann commented on iosSchool_HH/ViewController.swift
> +        let generateNameTwoClosure: () -> String = {
тоже можно многие одноразовые переменные не заводить, получится чище и короче

2023-11-06 08:18 UTC, Ytsyy commented on iosSchool_HH/FirstHomework.swift
> +    let generateNameTwoClosure: () -> String = {
1) Нельзя объявлять переменные около того места где они используются ? Если эти переменные нужны будут скажем всего в нескольких методах, то нельзя ли объявить переменную перед ними ?
2) Эта кложура используется в generateNameTwo, по условиям мы должны передать в этот метод какое то замыкание возвращающую string

2023-11-08 03:45 UTC, vaganova-ann requested changes

2023-11-08 05:59 UTC, vaganova-ann approved these changes

2023-11-08 06:15 UTC, merged